### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by ihategithubalot** [CaptainPStar/co10_Escape#122]
Traceback (most recent call last):
  File "C:\directories\co10_Escape-maste\compile_local.py", line 81, in <module>
    shutil.copyfile(missiondir + ".pbo", './Packed/Missions/'+mission['name']+'.'+ missionIsland['class']+'.pbo') #Copy build artifact
  File "C:\directories\Python\Python39\lib\shutil.py", line 265, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: './Packed/Missions/co10_Escape_BIS_NATO_vs_CSAT.Altis.pbo'

**Comment by ihategithubalot** [comment]
Where is the packed folder? I see it referenced here and in the scripts and don't see it in any repos.

**Comment by PUNlSHER** [comment]
Its not there by default you need to add the Packed folder manually in the root folder
