### ISSUE TITLE
Merge VN with main branch

### ISSUE THREAD

**Issue by ScruffyAT** [CaptainPStar/co10_Escape#130]
Need to check things that were changed or might not work:
-IEDs: https://github.com/NeoArmageddon/co10_Escape/commit/4ff514c97ce07b3d176ffd7af4c66708fcdf81b6
  Will it work? Add array to other versions. Add as parameter
-Templates: https://github.com/NeoArmageddon/co10_Escape/commit/0abf90224ad3f97a68014f540c4f40caffa2cc6b
  Should work. Add arrays to other versions
  Don't merge this commit: https://github.com/NeoArmageddon/co10_Escape/commit/8695e953d22544e19081041e7a43fcb012821838
-Random function: https://github.com/NeoArmageddon/co10_Escape/commit/a20205daa1ec70c62cc7cd16a52dbd6be4a26961
  Does this need to be fixed?
-maps and NVGs: https://github.com/NeoArmageddon/co10_Escape/commit/9d2594ce07a95419bb2acf71440991537da38509
  should work?
-gametype: https://github.com/NeoArmageddon/co10_Escape/commit/9d140e14220c2bb534a29ce2285ac34736b1427e
-dev packer update for mission.sqm unit traits needed?

**Comment by CaptainPStar** [comment]
Merged and vanilla tested. VN mods still needs to be checked.
