### ISSUE TITLE
AI spawning on objectives

### ISSUE THREAD

**Issue by N0FG** [CaptainPStar/co10_Escape#137]
Version 1.10 dev cf6a28a

The AI group number is too few and the group size on comms and ammo depots aren't scaling to player count when the option is used in the A3E_Param_EnemyGroupSize setting. (tested 1:1 and 1:1.5) The patrols, village markers and mortars seem to be fine, though the mortars need to be restricted in group count as the number of AI spawning there can get ridiculous, even for a single player. Even when set to "high" A3E_Param_EnemyGroupSize 7-9 the numbers aren't comparable to the release version's  Param_EnemyFrequency  5-7 setting.

Observed this on local editor (alone) and external server (1-6 players)....and a couple of Mildly_Interested's clan ocap recordings where the roadblocks had 2 groups of 2 AI with 5-7 players on.

On the release version, the mortar group count is similar (though not as often  5-6 groups) but the group size is restricted and only spawns 4-6 per group on high settings (compared to the 7-8 on dev). At the ammo and comms there are more groups containing higher AI numbers, but still restricts them to less than 7 AI in each group on high settings.

It's a reasonably urgent issue as it means using the dev version of the mission isn't really feasible  because those low numbers give a false instance of the mission and it's level of difficulty.

Some observations...

A3E_Param_EnemyGroupSize setting 2-3
mortar
1/ 2 groups 2 AI each
2/ 1 group of 2
3/ 5 groups 2 of 4, 3 of 1
4/ 5 groups 2 of 3, 3 of 2
5/ 1 group of 2

Ammo 
1/ 1 group of 2
2/ 1 group of 2
3/ 2 group of 2
4/ 1 group of 2
5/ 2 groups of 2

comms
1/ 1 group of 3
2/ 2 groups of 2
3/ 2 groups of 2
4/ 2 groups of 2

A3E_Param_EnemyGroupSize setting 7-9
mortar
1/ 5 groups of 7-8 each
2/ 3 groups of 7-8 each
3/ 3 groups of 8 
4/ 2 groups of 8 
5/ 5 groups of 7-8 each

Ammo 
1/ 3 groups 3 of 2, 1 of 1 
2/ 3 groups 3 of 2, 2 of 1
3/ 3 groups 3 of 2, 1 of 1 
4/ 3 groups of 3 
5/ 3 groups of 3 

comms
1/ 3 groups of 3
2/ 3 groups of 3
3/ 3 groups 2 of 3, 1 of 1
4/ 4 groups of 2

A3E_Param_EnemyGroupSize setting 1:1 (Same type results with 1:1.5)
mortar
1/ 6 groups 5 of 2, 1 of 4
2/ 4 groups 3 of 2, 1 of 3
3/ 4 groups 4 of 2
4/ 1 group of 2
5/ 5 groups 4 of 2, 1 of 4
6/ 6 groups 1 of 3, 5 of 2

Ammo 
1/ 3 groups of 1 
2/ 1 group of 2
3/ 2 groups of 1  
4/ 2 groups of 1  
5/ 2 groups of 1  
6/ 2 groups of 1 

comms
1/ 2 groups of 1
2/ 2 groups of 1
3/ 2 groups of 1
4/ 2 groups of 1

1.10 release
Param_EnemyFrequency setting 5-7
mortar
1/ 2 groups of 1
2/ 3 groups 2 of 2, 1 of 1
3/ 3 groups 2 of 2, 1 of 1
4/ 4 groups 3 of 2, 1 of 1
5/ 2 groups of 2

ammo 
1/ 3 groups of 5
2/ 3 groups of 4
3/ 3 groups 2 of 4, 1 of 6
4/ 3 groups 1 of 4, 2 of 5
5/ 3 groups 1 of 3, 2 of 5
6/ 3 groups 2 of 5, 1 of 4
7/ 3 groups of 4
8/ 3 groups 2 of 6, 1 of 4

comms
1/ 4 groups 1 of 4, 2 of 5, 1 of 3
2/ 4 groups 1 of 5, 2 of 6, 1 of 4
3/ 4 groups 3 of 6, 1 of 4
4/ 4 groups 3 of 6, 1 of 5

**Comment by CaptainPStar** [comment]
Fixed with 54fad240e6aeb146d8bab4ffdb9d3dca2b0bdf26
