### ISSUE TITLE
Warning Message: You cannot play/edit this mission

### ISSUE THREAD

**Issue by demosthenesk** [CaptainPStar/co10_Escape#152]
Hello, i put pbo files at mpmissions folder but when i start the server i get

Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.\na3_characters_f

Please help !

**Comment by CaptainPStar** [comment]
This means either your server is installed/started incorrectly or you are using an unofficial server installation. A3_characters_f is a default package that comes with A3 installation. 

So not a problem with the mission files.

**Comment by ScruffyAT** [comment]
Just to add here: This was resolved on discord, this error is a BIS problem and the error message is in every .rpt
