### ISSUE TITLE
New roadblock template missing from DLC 1944 Spearhead "rb_spe_rb1"

### ISSUE THREAD

**Issue by aussie-battler** [CaptainPStar/co10_Escape#164]
I noticed that a roadblock template is missing. No big deal, maybe its still in the making?

A3E_RoadblockTemplates = [
	"rb_spe_rb1"];
	
	Thanks for you hard work in making Escape 1944 happen :) great work.

**Comment by ScruffyAT** [comment]
The templates from the new IsoTemplate system are in https://github.com/CaptainPStar/co10_Escape/tree/master/Code/templates, not Code\functions\templates. It's only the roadblocks right now.

**Comment by aussie-battler** [comment]
Thanks, love your work mate.
