### ISSUE TITLE
Losing ammo when using mag repack

### ISSUE THREAD

**Issue by BeardedBushman** [CaptainPStar/co10_Escape#168]
I downloaded the latest build yesterday (2023-10-03 19:57:25) install it on my dedicated server, ran a mission (CUP Woodland RU vs USMC & RACS) on Chernarus, I was carrying an M16A2 with M203, I stopped to do a mag repack (not using the mission mag repack, but using QS Mag Repack mod) I prefer to use this one, anyway I was carrying x3 40mm grenades, one in the wepaon and x2 in my kit, did the usual repack and 2x 40mm disappeared, only the one left in the gun was present. I have not had this happen before in the older 1.10 missions that I have been running for 2-3 years.

**Comment by BeardedBushman** [comment]
Though if I have a full kit, I have to remove some things because if I dont and I do a mag repack, I lose side arm ammo from the kit. It has been this way for years, I just never reported it before.

**Comment by ScruffyAT** [comment]
Hi Bushman. I've seen some of your streams :)
Sorry, can't help with this issue. That's a problem of the addon, maybe it's worse with some other mod weapons if they use scripting or uncommon config stuff.
You can try the included script version, as it works differently and maybe doesn't have this (or just other) bugs. The addon version would be this one: https://steamcommunity.com/sharedfiles/filedetails/?id=1593431569
No idea if script and addon differ

**Comment by BeardedBushman** [comment]
I thought it would be the addon, I prefer QS repack as its faster & without a hud, just have to reload your weapons. (btw I always use CUP weapons) I might try the mission repack, been a long time since I used that one. Thx for the reply mate.
