### ISSUE TITLE
Al Salmon RHS US vs RU has no enemy troops

### ISSUE THREAD

**Issue by extratightpants** [CaptainPStar/co10_Escape#181]
Playing this RHS version, There were no enemy troops at prison, no patrols, no enemy at oil rigs, and no enemy at bases. I would maybe check the other RHS version too, which is RU vs US.

**Comment by extratightpants** [comment]
I would maybe check the other RHS version too, which is US vs RU.

**Comment by ScruffyAT** [comment]
Do you have SAF downloaded and active (server and client)? I think most versions need all 4 RHS mod parts.

**Comment by extratightpants** [comment]
@ScruffyAT you are right i was missing that one SAF module! sorry about that. That must clear up some of the other issues i was having on other maps.
