### ISSUE TITLE
Revive bug on non-dedicated server

### ISSUE THREAD

**Issue by extratightpants** [CaptainPStar/co10_Escape#183]
Hey,

I still have the revive bug when hosting a server in-game via internet option  (non dedicated server, non lan) using the latest build [b45f1b4].  I am using vanilla arma3 with no mods. Revive bug is the multiple death notifications and when reviving, player cannot stand up or move, cant reload.  A and D change the camera views to non player views.

The revive bug seems to occur randomly. Sometimes i can play a whole game with a friend with mulitple deaths and revives and then bam we will get the revive bug. Revive bug can happen from bullets or grenades. Sometimes there are 2 death notifications, sometimes 3. all very random. 

I tested with a friend in both vanilla and modded games. How we tested. Kill all prison guards, take their grenades and kill my friend to see if the revive bug happens.

**Comment by CaptainPStar** [comment]
Wait for the next Arma update to have this fixed and use a locally hosted dedicated server (-server for the default exe, works alongside a second client running).

Client-hosted was always buggy in Arma3 and is not supported for Escape.
